apiVersion: apps/v1
kind: Deployment
metadata:
  name: bird-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bird-frontend
  template:
    metadata:
      labels:
        app: bird-frontend
    spec:
      containers:
      - name: bird-frontend
        image: bruno74t/bird-frontend:v.1.0.5
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: bird-frontend-service
spec:
  selector:
    app: bird-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer